# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c301d5c943eb0aae2720b05005615bdd"
application_url = "https://gourmet-hb-autumn-crossword.trycloudflare.com"
embedded = true
name = "Efoli"
handle = "efoli-app"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://gourmet-hb-autumn-crossword.trycloudflare.com/auth/callback",
  "https://gourmet-hb-autumn-crossword.trycloudflare.com/auth/shopify/callback",
  "https://gourmet-hb-autumn-crossword.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
